project:
  type: website

website:
  title: "Programming and statistical modelling in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/index.qmd
        text: Lectures
      - href: exercises/index.qmd
        text: Exercises

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



