project:
  type: website
  output-dir: docs

website:
  title: "Programming and statistical modelling in R"
  navbar:
    logo: "ku-logo_400x400.png"
    background: "#901a1e"
    left:
      - href: index.qmd
        text: Home
      - href: lectures/index.qmd
        text: Lectures
      - href: exercises/index.qmd
        text: Exercises
      - href: resources.qmd
        text: Links and Resources
  repo-url: https://github.com/sachsmc/r-programming
  repo-actions: [issue]

format:
  html:
    theme: flatly
    #backgroundcolor: "#901a1e"
    css: styles.css
    toc: true



