---
title: "Project organization and workflow"
author: "Michael C Sachs"
format: revealjs
---



## R session and the working directory

```{r}
#| echo= TRUE
getwd()
list.dirs(".", recursive = FALSE)
list.dirs("..", recursive = FALSE)
```

- The R session runs in the current _working directory_ 
- Input and output happens relative to that directory
- `"."` means "this directory"
- `".."` means "the directory that this one is contained in"


## An example project structure

```{r ex}
twee <- function(path = getwd(), level = Inf) {
  
  fad <-
    list.files(path = path, recursive = TRUE,no.. = TRUE, include.dirs = TRUE)

  fad_split_up <- strsplit(fad, "/")

  too_deep <- lapply(fad_split_up, length) > level
  fad_split_up[too_deep] <- NULL
  
  jfun <- function(x) {
    n <- length(x)
    if(n > 1)
      x[n - 1] <- "|__"
    if(n > 2)
      x[1:(n - 2)] <- "   "
    x <- if(n == 1) c("-- ", x) else c("   ", x)
    x
  }
  fad_subbed_out <- lapply(fad_split_up, jfun)
  
  cat(unlist(lapply(fad_subbed_out, paste, collapse = "")), sep = "\n")
}

cat("example-project\n")
twee(here::here("example-project"))

```